### ISSUE TITLE
build error with zig 0.10.0

### ISSUE THREAD

**Issue by calvin2021y** [Arwalk/zig-protobuf#14]
./build.zig:24:13: error: no member named 'path' in struct 'std.build.Pkg'
            .path = std.build.FileSource{.path = "src/protobuf.zig"}

**Comment by Arwalk** [comment]
Will try to update to zig 0.10 tonight.

**Comment by Arwalk** [comment]
@calvin2021y zig 0.10.0 has not been released yet AFAIK. I'd prefer to upgrade to a stable version when it is released.

If you have an actual use case for the library that requires zig 0.10.0-dev and want to tinker with it, i can make an exception though. I can't refuse some feedback :)

Would you like me to upgrade it?

**Comment by calvin2021y** [comment]
Thanks for the kind response,  it will be great to upgrade for 0.10.0. (I guess we need upgrade soon or late.)

**Comment by Arwalk** [comment]
Well, once again, i'd have prefered to wait for a 0.10 official release. I will get the latest dev version and will precise the revision in the readme while upgrading.

**Comment by lbureau-billettiqueservices** [comment]
zig 0.10 has been officially released, i will update develop to rely on it.

**Comment by Arwalk** [comment]
@calvin2021y the branch `update_to_0.10` is compatible with the stage1 compiler of 0.10.0. Sadly i can't seem to make it work with the stage 2 compiler: my abuse of comptime doesn't seem to work there.

I might have to rethink a bit about how to redo most of my code if my assumptions about comptime aren't possible anymore. Welp.

**Comment by Arwalk** [comment]
solved by #16
