### ISSUE TITLE
Update to Zig `HEAD` version

### ISSUE THREAD

**Issue by Ev1lT3rm1nal** [Arwalk/zig-protobuf#35]
It is not running on either version 0.11.0 or the current zig master version (0.12.0-dev.2341+92211135f)

**Comment by Arwalk** [comment]
Looks like ZLS moved out of zpm. Gotta do something about the install.sh script of dev container too.

**Comment by Arwalk** [comment]
Ok, zig build system changed a lot and that impacts the ProtocStep builder.

Took a quick look already, WIP PR ongoing.

**Comment by Arwalk** [comment]
pr is working as-is but need some refinements. @Ev1lT3rm1nal if you can't wait a release you can pull the branch. I'm missing some details to make it proper.

**Comment by Ev1lT3rm1nal** [comment]
I'm ok with this, I haven't tried it yet tho.

**Comment by Arwalk** [comment]
In any case, thanks for the heads up.
