### ISSUE TITLE
Error loading library 

### ISSUE THREAD

**Issue by Arwalk** [Arwalk/zig-protobuf#41]
Hello, sabe problem here with zig `0.12.0-dev.3161+377ecc6af`. It can't find `protobuf` module and also complains that the project does not have a `build.zig.zon` file so `zig fetch --save` does not work.

_Originally posted by @davo417 in https://github.com/Arwalk/zig-protobuf/issues/37#issuecomment-1994442726_

**Comment by Arwalk** [comment]
> Hello, sabe problem here with zig `0.12.0-dev.3161+377ecc6af`. It can't find `protobuf` module and also complains that the project does not have a `build.zig.zon` file so `zig fetch --save` does not work.
> 
> _Originally posted by @davo417 in https://github.com/Arwalk/zig-protobuf/issues/37#issuecomment-1994442726_


Hello @davo417, do you have some code to share with us so we can check? Will look into it.

**Comment by davo417** [comment]
Works great!! Thank you for the prompt response.
