### ISSUE TITLE
How to use system/different `protoc`

### ISSUE THREAD

**Issue by james-callahan** [Arwalk/zig-protobuf#55]
From a supply chain security point of view I don't want zig-protobuf to provide its own protoc: I'd like to either use my system one, or possibly build it from source.
How can I tell zig-protobuf to use my system protoc?

**Comment by Arwalk** [comment]
Fair point, we might need to add options to RunProtoc. At first glance I'd say we need 

- download (current behaviour, default)
- use system provided through path encmv
- use user provided protoc
