### ISSUE TITLE
`dupe()` methods fail to compile

### ISSUE THREAD

**Issue by inge4pres** [Arwalk/zig-protobuf#74]
Hey there 👋🏼 
Reporting a possible bug that I just discovered when calling the `dupe` method for the first time.

I am unable to understand why, leet me know if I can provide more information to debug the issue.

**What happened**

I am trying to call `dupe()` on the root type of a deeply nested messages structure, with code generated from [this proto](https://github.com/open-telemetry/opentelemetry-proto/blob/ff457cecf46cf219602e587d86d66f3b8cb3efe6/proto-src/opentelemetry/proto/metrics/v1/metrics.proto#L56-L57).

Whan adding a call to any `dupe()` on each of the structs of this proto, I get a compilation error as follows

```
/.../src/protobuf.zig:488:50: error: unable to resolve inferred error set
                    try list.append(try item.dupe(allocator));
                                        ~~~~~~~~~^~~~~~~~~~~
referenced by:
    pb_dupe__anon_13682: /.../src/protobuf.zig:471:52
    dupe: /.../src/protobuf.zig:981:27
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Environment**

protobuf-zig: v1.0.6
Zig 0.13.0
Linux 6.10
Protoc 3.19.6 (not sure if relevant)

**Comment by Arwalk** [comment]
Hey there. Thank you for the issue. I'll look into it.

**Comment by Arwalk** [comment]
@inge4pres It would seem that for deeply nested structures with arraylists, zig had a hard time figuring out the error set automatically. Luckily dupe's only source of error types are allocations in ArrayList.append, so we can coerce to it and everything's fine afterwise.

Can you check and confirm that https://github.com/Arwalk/zig-protobuf/tree/74-dupe-methods-fail-to-compile fixes it for you? @inge4pres

**Comment by Arwalk** [comment]
Master should be updated. I'm a bit behind on releases to i'd just advise to use master for now.

**Comment by inge4pres** [comment]
> I'm a bit behind on releases to i'd just advise to use master for now.

nw at all! your commitment in maintaining this project is highly appreciated 🙏🏼 
I hope I can find some time to contribute back to this amazing project
